name: Run fine-tuning

# trigger when push on main
on:
  push:
    branches:
      - main

jobs:
  fine-tune-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv pip install -r requirements.txt
      - name: Run fine-tuning
        run: bash fine_tune.sh
