name: Run fine-tuning

# trigger when push on main
on:
  push:
    branches:
      - main

jobs:
  fine-tune-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run:
          pip install -r requirements.lock.txt
      # - name: Install setuptools
      #   run:
      #     pip install -U pyopenssl
      #     pip install setuptools==69.5.1
      - name: Run fine-tuning
        env:
          UNIONAI_SERVERLESS_API_KEY: ${{ secrets.UNIONAI_SERVERLESS_API_KEY_GCP }}
        run:
          unionai run --copy-all --remote
            llm_edge_finetuning/workflows_news.py train_workflow
            --config config/phi_3_mini_128k_instruct.json
            --categories '["science", "technology", "business"]'
