name: Run fine-tuning

# trigger when push on main
on:
  push:
    branches:
      - main

jobs:
  fine-tune-model:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
      - name: Install dependencies
        run:
          pip install uv
          pip install -U setuptools
          uv pip install -r requirements.lock.txt
      - name: Run fine-tuning
        run: bash fine_tune.sh
